language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO=1.4.13
  - DJANGO=1.5
  - DJANGO=1.5.8
  - DJANGO=1.6
  - DJANGO=1.6.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test geoposition
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.2
      env: DJANGO=1.4.13
    - python: 3.3
      env: DJANGO=1.4.13
    - python: 3.4
      env: DJANGO=1.4.13
